# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hoth}
  s.version = "0.0.17"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["pkw.de Development"]
  s.date = %q{2011-03-30}
  s.description = %q{Creating a SOA requires a centralized location to define all services within the
SOA. Furthermore you want to know where to deploy those services.
}
  s.email = %q{dev@pkw.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    "README.rdoc",
     "lib/hoth.rb",
     "lib/hoth/definition.rb",
     "lib/hoth/deployment_module.rb",
     "lib/hoth/endpoint.rb",
     "lib/hoth/exceptions.rb",
     "lib/hoth/extension/core/exception.rb",
     "lib/hoth/providers/rack_provider.rb",
     "lib/hoth/service.rb",
     "lib/hoth/service_deployment.rb",
     "lib/hoth/service_registry.rb",
     "lib/hoth/services.rb",
     "lib/hoth/transport/hoth_transport.rb",
     "lib/hoth/transport/json_transport.rb",
     "lib/hoth/util/logger.rb",
     "spec/hoth_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/definition_spec.rb",
     "spec/unit/deployment_module_spec.rb",
     "spec/unit/endpoint_spec.rb",
     "spec/unit/extension/core/exception_spec.rb",
     "spec/unit/providers/rack_provider_spec.rb",
     "spec/unit/service_spec.rb"
  ]
  s.homepage = %q{http://github.com/pkwde/hoth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Registry and deployment description abstraction for SOA-Services}
  s.test_files = [
    "spec/hoth_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/definition_spec.rb",
     "spec/unit/deployment_module_spec.rb",
     "spec/unit/endpoint_spec.rb",
     "spec/unit/extension/core/exception_spec.rb",
     "spec/unit/providers/rack_provider_spec.rb",
     "spec/unit/service_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<typhoeus>, ["~> 0.2.3"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<typhoeus>, ["~> 0.2.3"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<typhoeus>, ["~> 0.2.3"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

